<a href="https://colab.research.google.com/github/AceBlu/LetsUpgrade-Data-Science/blob/main/Day_3_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 3 Data Science Assignment



**Question 1.**
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
import numpy as np
ar = np.arange(2,50,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


**Question 2.**
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [20]:
lst1 = []
lst2 = []

print("Enter the value for List-1 : ")
for i in range(5):
  x=int(input(""))
  lst1.append(x)

print("\nEnter the value for List-2 : ")
for i in range(5):
  x=int(input(""))
  lst2.append(x)

arr1 = np.array(lst1)
arr2 = np.array(lst2)

arr = np.concatenate((arr1, arr2))
print("\nConcatenated Array :",arr)

sortArr = np.sort(arr)
print("\nSorted Array :",sortArr)

Enter the value for List-1 : 
1
3
5
7
9

Enter the value for List-2 : 
2
4
5
6
8

Concatenated Array : [1 3 5 7 9 2 4 5 6 8]

Sorted Array : [1 2 3 4 5 5 6 7 8 9]


**Question 3.**
Write a code snippet to find the dimensions of a ndarray and its size.

In [19]:
arr = np.array([[1,3,5],[2,6,8],[1,2,4]])
print("\nDimensions of array : ", arr.ndim)
print("\nSize of array : ", arr.size)



Dimensions of array :  2

Size of array :  9


**Question 4.**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [18]:
arr = np.arange(1,10)
print("Shape of 1d Array :",arr.shape)
row = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row.shape)

col = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col.shape)

Shape of 1d Array : (9,)

Shape of 2d Array in row major : (1, 9)

Shape of 2d Array in column major : (9, 1)


**Question 5.**
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [22]:
array1 = np.square([1,3,5,7,9])
array2 = np.square([2,4,6,8,10])

print("Horizontal Append :", np.hstack((array1, array2)))
print("\nVertical Append :", np.vstack((array1, array2)))

Horizontal Append : [  1   9  25  49  81   4  16  36  64 100]

Vertical Append : [[  1   9  25  49  81]
 [  4  16  36  64 100]]


**Question 6.**
How to get unique items and counts of unique items?

In [24]:
arr1 = np.array([2,3,4,56,1,2,4,6,3,3,3,5,10])
uniq, cnts = np.unique(arr1, return_counts=True)
arr = np.asarray((uniq, cnts)).T

print(arr)

[[ 1  1]
 [ 2  2]
 [ 3  4]
 [ 4  2]
 [ 5  1]
 [ 6  1]
 [10  1]
 [56  1]]
